---
- name: Load Variables
  tags: always
  block:
    - name: Load system variables
      ansible.builtin.include_vars:
        dir: ../vars/common
        ignore_unknown_extensions: true
    - name: Populate facts var
      ansible.builtin.include_vars:
        file: ../vars/facts/{{ ansible_connection }}-{{ ansible_facts['system'] }}.yml
    - name: Loading OS variables
      ansible.builtin.include_vars:
        dir: "{{ item }}"
        name: os
      tags: load_os_vars
      loop: >
        {{ query('first_found',
          [
            playbook_dir + '/vars/os/{{ facts_os_dist_ver }}.yml',
            playbook_dir + '/vars/os/{{ facts_distro_lower }}/{{ facts_distro_major }}'
          ],
          errors='ignore')
        }}
      loop_control:
        label: "{{ item | relpath(playbook_dir + '/vars/os/') }}"
    - name: Ensure OS variables are loaded
      ansible.builtin.assert:
        that: os is defined
        fail_msg: |
          Could not load any OS variables!
          Paths:
            '../vars/os/{{ facts_os_dist_ver }}.yml'
            '../vars/os/{{ facts_distro_lower }}/{{ facts_distro_major }}'
      tags: ensure_os_vars
- name: Show variables
  ansible.builtin.debug:
    var: ansible_included_var_files
  tags: LoadedVars
  when: "'LoadedVars' in ansible_run_tags"
- name: Get Variable
  ansible.builtin.debug:
    var: "{{ var }}"
  tags:
    - never
    - GetVar
    - get_var
    - Get Var
  when:
    - var is defined
# - name: Get Hosts
#   ansible.builtin.debug:
#     msg: "{{ ansible_play_hosts | map('extract', hostvars, 'ansible_host') }}"
#   tags:
#     - never
#     - GetHosts
#     - get_hosts
