---
sysadmin_path: "{{ playbook_dir }}/Play_sysAdmin"
sysadmin_tasks_path: "{{ sysadmin_path }}/tasks"
sysadmin_handlers_path: "{{ sysadmin_path }}/handlers"
sysadmin_templates_path: "{{ sysadmin_path }}/templates"
sysadmin_files_path: "{{ sysadmin_path }}/files"
