---
- hosts: "{{ target_hosts | mandatory }}"
  vars_files:
    - vars/play_sysadmin.yml
  handlers:
    - import_tasks: "{{ sysAdmin_handlers_path }}/network.yml"
    - import_tasks: "{{ sysAdmin_handlers_path }}/service.yml"
    - import_tasks: "{{ sysAdmin_handlers_path }}/system.yml"
  pre_tasks:
    - import_tasks: tasks/global-pre.yml
      tags: always
  tasks:
    - name: Ensure {{ role }} is assignet to {{ inventory_hostname }}
      assert:
        quiet: yes
        that:
          - roles is defined
          - role in roles
        fail_msg: "{{ role }} is not assigned to {{ inventory_hostname }}, if you still want to do this try with --skip-tags=force_role_definition"
      tags: 
        - always
        - force_role_definition
    - name: Import Role
      import_role: 
        name: "{{ role|mandatory }}"
  post_tasks:
    - import_tasks: tasks/global-post.yml
      tags: always