---
- hosts: "{{ target_hosts | mandatory }}"
  vars_files:
    - vars/play_sysadmin.yml
  handlers:
    - name: Import network related handlers
      ansible.builtin.import_tasks: "{{ sysadmin_handlers_path }}/network.yml"
    - name: Import service related handlers
      ansible.builtin.import_tasks: "{{ sysadmin_handlers_path }}/service.yml"
    - name: Import system related handlers
      ansible.builtin.import_tasks: "{{ sysadmin_handlers_path }}/system.yml"
  pre_tasks:
    - ansible.builtin.import_tasks: tasks/global-pre.yml
      tags: always
  tasks:
    - name: Import Role
      ansible.builtin.import_role:
        name: "{{ role | mandatory }}"
  post_tasks:
    - ansible.builtin.import_tasks: tasks/global-post.yml
      tags: always
