- hosts: localhost
  connection: local
  vars:
    tasks_path: "Play_init"
  # gather_facts: no
  tasks:
    - name: init vars
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob: "{{ ansible_facts.env.ANSIBLE_L_BASE }}/init/**.yml"
      loop_control:
        label: "{{ item|basename }}"
      tags: always
    - name: Ensuring roles
      ansible.builtin.git:
        dest: "{{ ansible_facts.env.ANSIBLE_L_SRC_PATH }}/roles/{{ role.key }}"
      args: "{{ role.value}}"
      loop: "{{ role_list|dict2items }}"
      loop_control:
        loop_var: role
        label: "{{ role.key }}"
      when: role_list is defined
      tags:
        - init-roles
        - roles
    - name: Ensure Inventories
      ansible.builtin.include_tasks:
        file: "{{ tasks_path }}/init-inv.yml"
        apply:
          tags:
            - init-inv
            - inventories
      loop: "{{ inv_list|dict2items }}"
      loop_control:
        loop_var: org
        label: "{{ org.key }}"
      tags:
        - init-inv
        - inventories
