---
- hosts: "{{ target_hosts | default('localhost') }}"
  vars_files:
    - vars/play_sysadmin.yml
  handlers:
    - import_tasks: "{{ sysadmin_handlers_path }}/network.yml"
    - import_tasks: "{{ sysadmin_handlers_path }}/service.yml"
    - import_tasks: "{{ sysadmin_handlers_path }}/system.yml"
  pre_tasks:
    - include_tasks: tasks/global-pre.yml
      tags: always
  tasks:
    - name: Pull image
      docker_image:
        name: "{{ remote_repo|default('') }}{{ image_name }}"
        tag: "{{ image_tag|default(omit) }}"
        source: pull
    - name: Tag and push image
      docker_image:
        name: "{{ remote_repo|default('') }}{{ image_name }}"
        repository: "{{ repo }}/{{ image_name }}"
        tag: "{{ image_tag|default(omit) }}"
        source: local
        push: true
  post_tasks:
    - include_tasks: tasks/global-post.yml
      tags: always
