---
- hosts: "{{ target_hosts | mandatory }}"
  vars_files:
    - vars/play_sysadmin.yml
  gather_facts: "{{ gather_facts|default(omit) }}"
  handlers:
    - name: Network handlers
      ansible.builtin.import_tasks: "{{ sysadmin_handlers_path }}/network.yml"
    - name: Service handlers
      ansible.builtin.import_tasks: "{{ sysadmin_handlers_path }}/service.yml"
    - name: System handlers
      ansible.builtin.import_tasks: "{{ sysadmin_handlers_path }}/system.yml"
  pre_tasks:
    - name: Global Pre Tasks
      ansible.builtin.import_tasks: tasks/global-pre.yml
      tags: always
  tasks:
    - name: Load OS tasks
      ansible.builtin.include_tasks:
        file: "{{ item }}"
        apply:
          tags: never
      with_fileglob: "{{ sysadmin_tasks_path }}/{{ facts_os_dist_ver }}/*.yml"
      loop_control:
        label: "{{ facts_os_dist_ver }}"
      # when: not item.endswith('tasks.yml')
      tags: always
    - name: Load Generic Tasks
      ansible.builtin.include_tasks:
        file: "{{ task_file }}"
        apply:
          tags: never
      with_fileglob: "{{ sysadmin_tasks_path }}/generic/*.yml"
      loop_control:
        loop_var: task_file
      tags: always
    - name: Local Facts
      ansible.builtin.debug:
        var: facts_local
      tags:
        - never
        - Get Local Facts
        - GetLocalFacts
    - name: Ansible Facts
      ansible.builtin.debug:
        var: ansible_facts
      tags:
        - never
        - Get Facts
        - GetFacts
        - get_facts
    - name: Get System Info
      block:
        - name: Set System info
          ansible.builtin.set_fact:
            system_info:
              connection: "{{ ansible_connection }}"
              host: "{{ ansible_host }}"
              port: "{{ ansible_port }}"
              system: "{{ facts_system|default('VARIABLE NOT DEFINED') }}"
              distro: "{{ facts_distro|default('VARIABLE NOT DEFINED') }}"
              distro_lower: "{{ facts_distro_lower|default('VARIABLE NOT DEFINED') }}"
              distro_major: "{{ facts_distro_major|default('VARIABLE NOT DEFINED') }}"
              os_dist_ver: "{{ facts_os_dist_ver|default('VARIABLE NOT DEFINED') }}"
              distro_release: "{{ facts_distro_release|default('VARIABLE NOT DEFINED') }}"
              os_info: "{{ facts_os_info|default('VARIABLE NOT DEFINED') }}"
        - name: Sysetm Info
          ansible.builtin.debug:
            var: system_info
      tags:
        - never
        - System Info
        - SystemInfo
    - name: Gen Import All tasks
      ansible.builtin.template:
        src: import_all.j2
        dest: "{{ sysadmin_path }}/import_all.yml"
        mode: 0644
      delegate_to: localhost
      when:
        - '"GenImportAllTasks" in ansible_run_tags '
    - name: Import All tasks
      ansible.builtin.import_tasks: "{{ sysadmin_path }}/import_all.yml"
      when:
        - '"get_tags" in ansible_run_tags '
  post_tasks:
    - name: Globl Post Tasks
      ansible.builtin.import_tasks: tasks/global-post.yml
