---
- hosts: "{{ target_hosts | mandatory }}"
  vars_files:
    - vars/play_sysadmin.yml
  gather_facts: "{{ gather_facts|default(omit) }}"
  handlers:
    - import_tasks: "{{ sysadmin_handlers_path }}/network.yml"
    - import_tasks: "{{ sysadmin_handlers_path }}/service.yml"
    - import_tasks: "{{ sysadmin_handlers_path }}/system.yml"
  pre_tasks:
    - name: Global Pre Tasks
      import_tasks: tasks/global-pre.yml
      tags: always
  tasks:
    - debug:
        msg: "{{ local_projects|community.general.json_query('*.dest.config_files[*].config.ConnectionStrings.*')|flatten|sort|unique  }}"
  # - debug:
  #     msg: "{{ ['ip_addresses']|map('extract', interfaces, ['address']) }}"
  #   delegate_to: localhost
  # - community.general.ldap_search:
  #     dn: "CN=Domain Admins,CN=Users,DC=FWUT,DC=xyz"
  #     bind_dn: "CN=ansible,CN=Users,DC=FWUT,DC=xyz"
  #     bind_pw: "W8pR?5&WFsaAG6Jp"
  #     scope: children
  #     # filter: "(&(memberOf=))"
  #     server_uri: "ldap://fwut.xyz"
  # - template:
  #     Dest: conf.d/"{{hostvars[item].bacula_client_config.Name}}"
  #   loop: "{{groups['grp_role_bacula_client']}}"
  # - name: Get all groups
  #   getent:
  #     database: passwd
  #     # split: ':'
  #   register: getent_passwd
  # - debug:
  #     var: getent_passwd
  # - name: Log lines to MS Teams
  #   office_365_connector_card:
  #     webhook: "https://fwutech109.webhook.office.com/webhookb2/1ac0a3c4-121f-4cff-9d54-0c9226ca0439@de9b08eb-f42e-4788-9d44-e615bd27d2ad/IncomingWebhook/d3aa5118d0d840fd908d890f10391b5f/06b7393f-15ce-4f05-a91a-962fd3dcb388"
  #     summary: This is the summary property
  #     title: This is the **card's title** property
  #     text: This is the **card's text** property. Lorem ipsum dolor sit amet, consectetur
  #       adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #     color: E81123
  #     sections:
  #     - title: This is the **section's title** property
  #       activity_image: http://connectorsdemo.azurewebsites.net/images/MSC12_Oscar_002.jpg
  #       activity_title: This is the section's **activityTitle** property
  #       activity_subtitle: This is the section's **activitySubtitle** property
  #       activity_text: This is the section's **activityText** property.
  #       hero_image:
  #         image: http://connectorsdemo.azurewebsites.net/images/WIN12_Scene_01.jpg
  #         title: This is the image's alternate text
  #       text: This is the section's text property. Lorem ipsum dolor sit amet, consectetur
  #         adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #       facts:
  #       - name: This is a fact name
  #         value: This is a fact value
  #       - name: This is a fact name
  #         value: This is a fact value
  #       - name: This is a fact name
  #         value: This is a fact value
  #       images:
  #       - image: http://connectorsdemo.azurewebsites.net/images/MicrosoftSurface_024_Cafe_OH-06315_VS_R1c.jpg
  #         title: This is the image's alternate text
  #       - image: http://connectorsdemo.azurewebsites.net/images/WIN12_Scene_01.jpg
  #         title: This is the image's alternate text
  #       - image: http://connectorsdemo.azurewebsites.net/images/WIN12_Anthony_02.jpg
  #         title: This is the image's alternate text
  #       actions:
  #       - "@type": ActionCard
  #         name: Comment
  #         inputs:
  #         - "@type": TextInput
  #           id: comment
  #           is_multiline: true
  #           title: Input's title property
  #         actions:
  #         - "@type": HttpPOST
  #           name: Save
  #           target: http://...
  #       - "@type": ActionCard
  #         name: Due Date
  #         inputs:
  #         - "@type": DateInput
  #           id: dueDate
  #           title: Input's title property
  #         actions:
  #         - "@type": HttpPOST
  #           name: Save
  #           target: http://...
  #       - "@type": HttpPOST
  #         name: Action's name prop.
  #         target: http://...
  #       - "@type": OpenUri
  #         name: Action's name prop
  #         targets:
  #         - os: default
  #           uri: http://...
  #     - start_group: true
  #       title: This is the title of a **second section**
  #       text: This second section is visually separated from the first one by setting its
  #         **startGroup** property to true.

  post_tasks:
    - include_tasks: tasks/global-post.yml
      tags: always
