---
- hosts: "{{ target_hosts | mandatory }}"
  vars_files:
    - vars/play_sysadmin.yml
  gather_facts: "{{ gather_facts|default(omit) }}"
  handlers:
    - import_tasks: "{{ sysadmin_handlers_path }}/network.yml"
    - import_tasks: "{{ sysadmin_handlers_path }}/service.yml"
    - import_tasks: "{{ sysadmin_handlers_path }}/system.yml"
  pre_tasks:
    - name: Global Pre Tasks
      import_tasks: tasks/global-pre.yml
      tags: always
  tasks:
    - name: Check for plugin directory
      ansible.builtin.assert:
        that:
          - "'/master/doc/_Good_WP_/data/plugins/{{ plugin|mandatory }}' is directory"

