---
facts_system: "{{ ansible_facts['system'] }}"
facts_distro: "{{ ansible_facts['os_family'] }}"
facts_distro_lower: "{{ facts_distro|lower }}"
facts_distro_major: "{{ ansible_facts['distribution_major_version'] }}"
facts_os_dist_ver: "{{ facts_distro|lower }}_{{ facts_distro_major }}"
facts_distro_release: "{{ ansible_facts['os_installation_type'] }}"
facts_os_info: "{{ facts_system }}: {{ facts_distro }} {{ ansible_facts['distribution_version'] }} '{{ facts_distro_release }}'"
facts_local: "{{ ansible_facts['ansible_local'] }}"